Fix to weird CDDB behavior w.r.t. fetching metadata.
Sometimes CDDB says that an entry for a particular disc exists,
but that entry is empty. This works around that.

diff --git a/shreds b/shreds
--- a/shreds
+++ b/shreds
@@ -88,6 +88,12 @@ sanitize() {
 cddb query "$DISC_INFO"
 CDDB_LISTING="`cddb_file query \"$DISC_INFO\"`"
 CDDB_STATUS=$(head -c3 "$CDDB_LISTING")
+if [ -z "$CDDB_STATUS" ];
+then
+    echo "ERROR: Could not contact CDDB"
+    rm -f "$CDDB_LISTING"
+    exit $E_CDDB_READ_FAILED
+fi
 SELECTED_DISC=
 echo "cddb query status is $CDDB_STATUS"
 if [ "$CDDB_STATUS" -eq 210 -o "$CDDB_STATUS" -eq 211 ];
@@ -111,19 +117,30 @@ else
     exit $CDDB_STATUS
 fi
 
+got_metadata=
 if [ -n "$SELECTED_DISC" ];
 then
     cddb read "$SELECTED_DISC"
     CDDB_METADATA="`cddb_file read \"$SELECTED_DISC\"`"
     CDDB_STATUS="$(head -c3 "$CDDB_METADATA")"
-    if [ ! "$CDDB_STATUS" -eq 210 ];
+    # N.B.: Occasionally, the status comes back as including a listing,
+    # but that listing is actually empty; in that case we just skip it
+    # and generate dummy values below
+    if [ -n "$CDDB_STATUS" ];
     then
-	echo "Could not read $SELECTED_DISC metadata from CDDB"
-	exit $E_CDDB_READ_FAILED
+        got_metadata=true
+        if [ ! "$CDDB_STATUS" -eq 210 ];
+        then
+	    echo "Could not read $SELECTED_DISC metadata from CDDB"
+            exit $E_CDDB_READ_FAILED
+        fi
+        # this is the nicely formatted metadata file we will be dealing with
+        METADATA_FILE="${CDDB_METADATA}-formatted"
     fi
-    # this is the nicely formatted metadata file we will be dealing with
-    METADATA_FILE="${CDDB_METADATA}-formatted"
-else
+fi
+
+if [ -z "got_metadata" ];
+then
     METADATA_FILE="`cddb_file read \"${DISC_ID}\"`-formatted"
     TRACK_COUNT=`echo $DISC_INFO | cut -d\  -f2`
     # Write a dummy metadata file
